### ISSUE TITLE
Bug in xml header

### ISSUE THREAD

**Issue by brooksambrose** [berteh/synfig-import-labels#17]
I'm using OSX Sierra with Synfig 1.2.0. Running the synfig-import-labels plugin yields the error:
```
Unable to load "/.../10script.sifz.1A603114":

Document not well-formed.
Line 1, column 1 (fatal):
Extra content at the end of the document
```

The top of that file reads:
```
<?xml version='1.0' encoding='utf-8'?>
```

Manually changing the single quotes to double fixes it:
```
<?xml version="1.0" encoding="utf-8"?>
```
The file loads normally.

**Comment by berteh** [comment]
thanks @brooksambrose for the catch, if you where talking about the example file ``test/out-commandline.sif``. Should now be fixed.

If you were referring to another file could you please tell me which one, or how you generated it... because Synfig makes a temporary copy of files when a script works on it... and thus I can't find it from your issue report.

thanks for taking the time to report this issue.

**Comment by brooksambrose** [comment]
Maybe it's a problem with Synfig then not your plugin. I ran your plugin from the plugin menu on an existing project, and then Synfig spit the error when trying to load one of the temporary project files it made, I assume while executing the plugin. The temporary '.sif' files generated during the the execution of the plugin are written with single quotes in the header.
